apiVersion: v1
kind: ConfigMap
metadata:
  name: wealthpath-config
  namespace: wealthpath
data:
  DATABASE_HOST: "postgres"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "wealthpath"
  DATABASE_SSLMODE: "disable"

