apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wealthpath

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres-init-configmap.yaml
  - postgres.yaml
  - backend.yaml
  - frontend.yaml
  - ingress.yaml

