apiVersion: v1
kind: Secret
metadata:
  name: wealthpath-secret
  namespace: wealthpath
type: Opaque
stringData:
  DATABASE_USER: "wealthpath"
  DATABASE_PASSWORD: "wealthpath123"
  JWT_SECRET: "k8s-local-dev-secret-change-in-production"
  POSTGRES_USER: "wealthpath"
  POSTGRES_PASSWORD: "wealthpath123"
  POSTGRES_DB: "wealthpath"

